# Generated by Django 5.0.7 on 2024-07-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmCurso', models.CharField(max_length=100)),
                ('tpCurso', models.CharField(choices=[('Continuo', 'Continuo'), ('Pontual', 'Pontual')], max_length=10)),
                ('dtInicio', models.DateTimeField()),
                ('dtFinalPrevista', models.DateTimeField()),
                ('dtFinalEfetiva', models.DateTimeField()),
            ],
        ),
    ]
