# Generated by Django 5.0.7 on 2024-07-30 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrainCads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAluno', models.CharField(max_length=100)),
                ('dataNascimento', models.DateTimeField()),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('cpfAluno', models.IntegerField()),
                ('emailAluno', models.CharField(max_length=100)),
                ('dataCadastro', models.DateTimeField(auto_now_add=True)),
                ('celularAluno', models.IntegerField()),
                ('endereco', models.CharField(max_length=200)),
                ('respFinanceiro', models.BooleanField(default=True)),
                ('respPedagogico', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Formulário de Aluno',
                'verbose_name_plural': 'Formulários de Aluno',
                'ordering': ['-dataCadastro'],
            },
        ),
        migrations.AlterModelOptions(
            name='cursos',
            options={'ordering': ['-dtInicio'], 'verbose_name': 'Cadastro de curso', 'verbose_name_plural': 'Cadastros de cursos'},
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='dtFinalEfetiva',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='dtFinalPrevista',
        ),
        migrations.AddField(
            model_name='cursos',
            name='descricao',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpParente', models.CharField(choices=[('M', 'Mãe'), ('P', 'Pai'), ('I', 'Irmã(o)'), ('A', 'Avós')], default='M', max_length=1)),
                ('nome', models.CharField(max_length=100)),
                ('dataNascimento', models.DateTimeField()),
                ('cpfParen', models.IntegerField()),
                ('emailParen', models.CharField(max_length=100)),
                ('dataCadastro', models.DateTimeField(auto_now_add=True)),
                ('celularParen', models.IntegerField()),
                ('endereco', models.CharField(max_length=200)),
                ('respFinanceiro', models.BooleanField(default=True)),
                ('respPedagogico', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrainCads.aluno')),
            ],
            options={
                'verbose_name': 'Formulário de Responsável',
                'verbose_name_plural': 'Formulários de Responsável',
                'ordering': ['-dataCadastro'],
            },
        ),
    ]
